//example time: JBFcrasher N64 Thunder Park Damn the Torpedoes 1:23.45


function applycss(){
let dcbfgi1r="AxlThunder"; let dcbfgi1c="AxlThunder"; let dcbfgi1t="1:21.52"; let dcbfgi1a="https://www.youtube.com/watch?v=0qVxl6PueuQ";	var myElementdcbfgi1 = document.getElementById("dcbfgi1");if(myElementdcbfgi1){ document.getElementById("dcbfgi1l").textContent = dcbfgi1t;document.getElementById("dcbfgi1").classList.add(dcbfgi1r);}	var myElementdcbfgi1p = document.getElementById("dcbfgi1p");if(myElementdcbfgi1p){ document.getElementById("dcbfgi1d").textContent = dcbfgi1t;document.getElementById("dcbfgi1p").classList.add(dcbfgi1r);var a = document.getElementById('dcbfgi1d');a.href = dcbfgi1a;document.getElementById("dcbfgi1r").textContent = dcbfgi1c}
let dcbfli1r="AxlThunder"; let dcbfli1c="AxlThunder"; let dcbfli1t="1:24.08"; let dcbfli1a="https://www.youtube.com/watch?v=8xgGGFmWdzQ";	var myElementdcbfli1 = document.getElementById("dcbfli1");if(myElementdcbfli1){ document.getElementById("dcbfli1l").textContent = dcbfli1t;document.getElementById("dcbfli1").classList.add(dcbfli1r);}	var myElementdcbfli1p = document.getElementById("dcbfli1p");if(myElementdcbfli1p){ document.getElementById("dcbfli1d").textContent = dcbfli1t;document.getElementById("dcbfli1p").classList.add(dcbfli1r);var a = document.getElementById('dcbfli1d');a.href = dcbfli1a;document.getElementById("dcbfli1r").textContent = dcbfli1c}
let dcbfsg1r="AxlThunder"; let dcbfsg1c="AxlThunder"; let dcbfsg1t="1:26.75"; let dcbfsg1a="https://www.youtube.com/watch?v=UuzAz5GfNog";	var myElementdcbfsg1 = document.getElementById("dcbfsg1");if(myElementdcbfsg1){ document.getElementById("dcbfsg1l").textContent = dcbfsg1t;document.getElementById("dcbfsg1").classList.add(dcbfsg1r);}	var myElementdcbfsg1p = document.getElementById("dcbfsg1p");if(myElementdcbfsg1p){ document.getElementById("dcbfsg1d").textContent = dcbfsg1t;document.getElementById("dcbfsg1p").classList.add(dcbfsg1r);var a = document.getElementById('dcbfsg1d');a.href = dcbfsg1a;document.getElementById("dcbfsg1r").textContent = dcbfsg1c}
let dcrhgi1r="AxlThunder"; let dcrhgi1c="AxlThunder"; let dcrhgi1t="1:26.25"; let dcrhgi1a="https://www.youtube.com/watch?v=B2_evQM4d88";	var myElementdcrhgi1 = document.getElementById("dcrhgi1");if(myElementdcrhgi1){ document.getElementById("dcrhgi1l").textContent = dcrhgi1t;document.getElementById("dcrhgi1").classList.add(dcrhgi1r);}	var myElementdcrhgi1p = document.getElementById("dcrhgi1p");if(myElementdcrhgi1p){ document.getElementById("dcrhgi1d").textContent = dcrhgi1t;document.getElementById("dcrhgi1p").classList.add(dcrhgi1r);var a = document.getElementById('dcrhgi1d');a.href = dcrhgi1a;document.getElementById("dcrhgi1r").textContent = dcrhgi1c}
let nibfna1r="Gamedraco"; let nibfna1c="Gamedraco"; let nibfna1t="2:44.40"; let nibfna1a="https://www.youtube.com/watch?v=xeFMb4eP05Y&t=1s";	var myElementnibfna1 = document.getElementById("nibfna1");if(myElementnibfna1){ document.getElementById("nibfna1l").textContent = nibfna1t;document.getElementById("nibfna1").classList.add(nibfna1r);}	var myElementnibfna1p = document.getElementById("nibfna1p");if(myElementnibfna1p){ document.getElementById("nibfna1d").textContent = nibfna1t;document.getElementById("nibfna1p").classList.add(nibfna1r);var a = document.getElementById('nibfna1d');a.href = nibfna1a;document.getElementById("nibfna1r").textContent = nibfna1c}
let nirhac1r="Gamedraco"; let nirhac1c="Gamedraco"; let nirhac1t="1:33.79"; let nirhac1a="https://www.youtube.com/watch?v=nOOIJa7WsMo";	var myElementnirhac1 = document.getElementById("nirhac1");if(myElementnirhac1){ document.getElementById("nirhac1l").textContent = nirhac1t;document.getElementById("nirhac1").classList.add(nirhac1r);}	var myElementnirhac1p = document.getElementById("nirhac1p");if(myElementnirhac1p){ document.getElementById("nirhac1d").textContent = nirhac1t;document.getElementById("nirhac1p").classList.add(nirhac1r);var a = document.getElementById('nirhac1d');a.href = nirhac1a;document.getElementById("nirhac1r").textContent = nirhac1c}
let nirhfe1r="Gamedraco"; let nirhfe1c="Gamedraco"; let nirhfe1t="1:25.43"; let nirhfe1a="https://www.youtube.com/watch?v=OKjYxLI12ak";	var myElementnirhfe1 = document.getElementById("nirhfe1");if(myElementnirhfe1){ document.getElementById("nirhfe1l").textContent = nirhfe1t;document.getElementById("nirhfe1").classList.add(nirhfe1r);}	var myElementnirhfe1p = document.getElementById("nirhfe1p");if(myElementnirhfe1p){ document.getElementById("nirhfe1d").textContent = nirhfe1t;document.getElementById("nirhfe1p").classList.add(nirhfe1r);var a = document.getElementById('nirhfe1d');a.href = nirhfe1a;document.getElementById("nirhfe1r").textContent = nirhfe1c}
let nitbac1r="LazyComet"; let nitbac1c="Lazy Comet"; let nitbac1t="1:50.32"; let nitbac1a="https://www.twitch.tv/videos/1441988243";	var myElementnitbac1 = document.getElementById("nitbac1");if(myElementnitbac1){ document.getElementById("nitbac1l").textContent = nitbac1t;document.getElementById("nitbac1").classList.add(nitbac1r);}	var myElementnitbac1p = document.getElementById("nitbac1p");if(myElementnitbac1p){ document.getElementById("nitbac1d").textContent = nitbac1t;document.getElementById("nitbac1p").classList.add(nitbac1r);var a = document.getElementById('nitbac1d');a.href = nitbac1a;document.getElementById("nitbac1r").textContent = nitbac1c}
let nitbgi1r="LazyComet"; let nitbgi1c="Lazy Comet"; let nitbgi1t="1:41.85"; let nitbgi1a="https://www.twitch.tv/videos/1445009095";	var myElementnitbgi1 = document.getElementById("nitbgi1");if(myElementnitbgi1){ document.getElementById("nitbgi1l").textContent = nitbgi1t;document.getElementById("nitbgi1").classList.add(nitbgi1r);}	var myElementnitbgi1p = document.getElementById("nitbgi1p");if(myElementnitbgi1p){ document.getElementById("nitbgi1d").textContent = nitbgi1t;document.getElementById("nitbgi1p").classList.add(nitbgi1r);var a = document.getElementById('nitbgi1d');a.href = nitbgi1a;document.getElementById("nitbgi1r").textContent = nitbgi1c}
let nitblp1r="LazyComet"; let nitblp1c="Lazy Comet"; let nitblp1t="1:54.78"; let nitblp1a="https://www.twitch.tv/videos/1445009092";	var myElementnitblp1 = document.getElementById("nitblp1");if(myElementnitblp1){ document.getElementById("nitblp1l").textContent = nitblp1t;document.getElementById("nitblp1").classList.add(nitblp1r);}	var myElementnitblp1p = document.getElementById("nitblp1p");if(myElementnitblp1p){ document.getElementById("nitblp1d").textContent = nitblp1t;document.getElementById("nitblp1p").classList.add(nitblp1r);var a = document.getElementById('nitblp1d');a.href = nitblp1a;document.getElementById("nitblp1r").textContent = nitblp1c}
let nitbli1r="LazyComet"; let nitbli1c="Lazy Comet"; let nitbli1t="1:46.06"; let nitbli1a="https://www.twitch.tv/videos/1441988245";	var myElementnitbli1 = document.getElementById("nitbli1");if(myElementnitbli1){ document.getElementById("nitbli1l").textContent = nitbli1t;document.getElementById("nitbli1").classList.add(nitbli1r);}	var myElementnitbli1p = document.getElementById("nitbli1p");if(myElementnitbli1p){ document.getElementById("nitbli1d").textContent = nitbli1t;document.getElementById("nitbli1p").classList.add(nitbli1r);var a = document.getElementById('nitbli1d');a.href = nitbli1a;document.getElementById("nitbli1r").textContent = nitbli1c}
let nitbny1r="LazyComet"; let nitbny1c="Lazy Comet"; let nitbny1t="1:48.75"; let nitbny1a="https://www.twitch.tv/videos/1445009093";	var myElementnitbny1 = document.getElementById("nitbny1");if(myElementnitbny1){ document.getElementById("nitbny1l").textContent = nitbny1t;document.getElementById("nitbny1").classList.add(nitbny1r);}	var myElementnitbny1p = document.getElementById("nitbny1p");if(myElementnitbny1p){ document.getElementById("nitbny1d").textContent = nitbny1t;document.getElementById("nitbny1p").classList.add(nitbny1r);var a = document.getElementById('nitbny1d');a.href = nitbny1a;document.getElementById("nitbny1r").textContent = nitbny1c}
let nitbna1r="LazyComet"; let nitbna1c="Lazy Comet"; let nitbna1t="3:15.76"; let nitbna1a="https://www.twitch.tv/videos/1441988246";	var myElementnitbna1 = document.getElementById("nitbna1");if(myElementnitbna1){ document.getElementById("nitbna1l").textContent = nitbna1t;document.getElementById("nitbna1").classList.add(nitbna1r);}	var myElementnitbna1p = document.getElementById("nitbna1p");if(myElementnitbna1p){ document.getElementById("nitbna1d").textContent = nitbna1t;document.getElementById("nitbna1p").classList.add(nitbna1r);var a = document.getElementById('nitbna1d');a.href = nitbna1a;document.getElementById("nitbna1r").textContent = nitbna1c}
let nitbsg1r="LazyComet"; let nitbsg1c="Lazy Comet"; let nitbsg1t="1:41.96"; let nitbsg1a="https://www.twitch.tv/videos/1445009094";	var myElementnitbsg1 = document.getElementById("nitbsg1");if(myElementnitbsg1){ document.getElementById("nitbsg1l").textContent = nitbsg1t;document.getElementById("nitbsg1").classList.add(nitbsg1r);}	var myElementnitbsg1p = document.getElementById("nitbsg1p");if(myElementnitbsg1p){ document.getElementById("nitbsg1d").textContent = nitbsg1t;document.getElementById("nitbsg1p").classList.add(nitbsg1r);var a = document.getElementById('nitbsg1d');a.href = nitbsg1a;document.getElementById("nitbsg1r").textContent = nitbsg1c}
let nitbfe1r="LazyComet"; let nitbfe1c="Lazy Comet"; let nitbfe1t="1:39.82"; let nitbfe1a="https://www.twitch.tv/videos/1445009096";	var myElementnitbfe1 = document.getElementById("nitbfe1");if(myElementnitbfe1){ document.getElementById("nitbfe1l").textContent = nitbfe1t;document.getElementById("nitbfe1").classList.add(nitbfe1r);}	var myElementnitbfe1p = document.getElementById("nitbfe1p");if(myElementnitbfe1p){ document.getElementById("nitbfe1d").textContent = nitbfe1t;document.getElementById("nitbfe1p").classList.add(nitbfe1r);var a = document.getElementById('nitbfe1d');a.href = nitbfe1a;document.getElementById("nitbfe1r").textContent = nitbfe1c}
let nitbvc1r="LazyComet"; let nitbvc1c="Lazy Comet"; let nitbvc1t="1:30.99"; let nitbvc1a="https://www.twitch.tv/videos/1445009090";	var myElementnitbvc1 = document.getElementById("nitbvc1");if(myElementnitbvc1){ document.getElementById("nitbvc1l").textContent = nitbvc1t;document.getElementById("nitbvc1").classList.add(nitbvc1r);}	var myElementnitbvc1p = document.getElementById("nitbvc1p");if(myElementnitbvc1p){ document.getElementById("nitbvc1d").textContent = nitbvc1t;document.getElementById("nitbvc1p").classList.add(nitbvc1r);var a = document.getElementById('nitbvc1d');a.href = nitbvc1a;document.getElementById("nitbvc1r").textContent = nitbvc1c}
let pcarli1r="AxlThunder"; let pcarli1c="AxlThunder"; let pcarli1t="1:36.86"; let pcarli1a="https://www.youtube.com/watch?v=iHgbVQKXUWo";	var myElementpcarli1 = document.getElementById("pcarli1");if(myElementpcarli1){ document.getElementById("pcarli1l").textContent = pcarli1t;document.getElementById("pcarli1").classList.add(pcarli1r);}	var myElementpcarli1p = document.getElementById("pcarli1p");if(myElementpcarli1p){ document.getElementById("pcarli1d").textContent = pcarli1t;document.getElementById("pcarli1p").classList.add(pcarli1r);var a = document.getElementById('pcarli1d');a.href = pcarli1a;document.getElementById("pcarli1r").textContent = pcarli1c}
let pcarvc1r="WeenieWhistle"; let pcarvc1c="WeenieWhistle"; let pcarvc1t="1:19.43"; let pcarvc1a="https://youtu.be/rl6L6onWTyo";	var myElementpcarvc1 = document.getElementById("pcarvc1");if(myElementpcarvc1){ document.getElementById("pcarvc1l").textContent = pcarvc1t;document.getElementById("pcarvc1").classList.add(pcarvc1r);}	var myElementpcarvc1p = document.getElementById("pcarvc1p");if(myElementpcarvc1p){ document.getElementById("pcarvc1d").textContent = pcarvc1t;document.getElementById("pcarvc1p").classList.add(pcarvc1r);var a = document.getElementById('pcarvc1d');a.href = pcarvc1a;document.getElementById("pcarvc1r").textContent = pcarvc1c}
let pcarvc2r="AxlThunder"; let pcarvc2c="AxlThunder"; let pcarvc2t="1:19.89"; let pcarvc2a="https://www.youtube.com/watch?v=Sl1HWo1ZihE";	var myElementpcarvc2 = document.getElementById("pcarvc2");if(myElementpcarvc2){ document.getElementById("pcarvc2l").textContent = pcarvc2t;document.getElementById("pcarvc2").classList.add(pcarvc2r);}	var myElementpcarvc2p = document.getElementById("pcarvc2p");if(myElementpcarvc2p){ document.getElementById("pcarvc2d").textContent = pcarvc2t;document.getElementById("pcarvc2p").classList.add(pcarvc2r);var a = document.getElementById('pcarvc2d');a.href = pcarvc2a;document.getElementById("pcarvc2r").textContent = pcarvc2c}
let pcctgi1r="AxlThunder"; let pcctgi1c="AxlThunder"; let pcctgi1t="1:17.39"; let pcctgi1a="https://www.youtube.com/watch?v=SIO4W85xzmg";	var myElementpcctgi1 = document.getElementById("pcctgi1");if(myElementpcctgi1){ document.getElementById("pcctgi1l").textContent = pcctgi1t;document.getElementById("pcctgi1").classList.add(pcctgi1r);}	var myElementpcctgi1p = document.getElementById("pcctgi1p");if(myElementpcctgi1p){ document.getElementById("pcctgi1d").textContent = pcctgi1t;document.getElementById("pcctgi1p").classList.add(pcctgi1r);var a = document.getElementById('pcctgi1d');a.href = pcctgi1a;document.getElementById("pcctgi1r").textContent = pcctgi1c}
let pcrhli1r="AxlThunder"; let pcrhli1c="AxlThunder"; let pcrhli1t="1:26.86"; let pcrhli1a="https://www.youtube.com/watch?v=M5Fn4Lfc4Eo";	var myElementpcrhli1 = document.getElementById("pcrhli1");if(myElementpcrhli1){ document.getElementById("pcrhli1l").textContent = pcrhli1t;document.getElementById("pcrhli1").classList.add(pcrhli1r);}	var myElementpcrhli1p = document.getElementById("pcrhli1p");if(myElementpcrhli1p){ document.getElementById("pcrhli1d").textContent = pcrhli1t;document.getElementById("pcrhli1p").classList.add(pcrhli1r);var a = document.getElementById('pcrhli1d');a.href = pcrhli1a;document.getElementById("pcrhli1r").textContent = pcrhli1c}
let pcrbli1r="AxlThunder"; let pcrbli1c="AxlThunder"; let pcrbli1t="1:31.89"; let pcrbli1a="https://www.youtube.com/watch?v=V1flcTZ8TCw";	var myElementpcrbli1 = document.getElementById("pcrbli1");if(myElementpcrbli1){ document.getElementById("pcrbli1l").textContent = pcrbli1t;document.getElementById("pcrbli1").classList.add(pcrbli1r);}	var myElementpcrbli1p = document.getElementById("pcrbli1p");if(myElementpcrbli1p){ document.getElementById("pcrbli1d").textContent = pcrbli1t;document.getElementById("pcrbli1p").classList.add(pcrbli1r);var a = document.getElementById('pcrbli1d');a.href = pcrbli1a;document.getElementById("pcrbli1r").textContent = pcrbli1c}
let pctblp1r="AxlThunder"; let pctblp1c="AxlThunder"; let pctblp1t="1:38.79"; let pctblp1a="https://www.youtube.com/watch?v=sTNq-KkcWXo";	var myElementpctblp1 = document.getElementById("pctblp1");if(myElementpctblp1){ document.getElementById("pctblp1l").textContent = pctblp1t;document.getElementById("pctblp1").classList.add(pctblp1r);}	var myElementpctblp1p = document.getElementById("pctblp1p");if(myElementpctblp1p){ document.getElementById("pctblp1d").textContent = pctblp1t;document.getElementById("pctblp1p").classList.add(pctblp1r);var a = document.getElementById('pctblp1d');a.href = pctblp1a;document.getElementById("pctblp1r").textContent = pctblp1c}
let pctbli1r="AxlThunder"; let pctbli1c="AxlThunder"; let pctbli1t="1:33.32"; let pctbli1a="https://www.youtube.com/watch?v=EpnQNmZM6xU";	var myElementpctbli1 = document.getElementById("pctbli1");if(myElementpctbli1){ document.getElementById("pctbli1l").textContent = pctbli1t;document.getElementById("pctbli1").classList.add(pctbli1r);}	var myElementpctbli1p = document.getElementById("pctbli1p");if(myElementpctbli1p){ document.getElementById("pctbli1d").textContent = pctbli1t;document.getElementById("pctbli1p").classList.add(pctbli1r);var a = document.getElementById('pctbli1d');a.href = pctbli1a;document.getElementById("pctbli1r").textContent = pctbli1c}
let psrhac1r="Gamedraco"; let psrhac1c="Gamedraco"; let psrhac1t="1:36.42"; let psrhac1a="https://www.youtube.com/watch?v=zGz7anGg2co";	var myElementpsrhac1 = document.getElementById("psrhac1");if(myElementpsrhac1){ document.getElementById("psrhac1l").textContent = psrhac1t;document.getElementById("psrhac1").classList.add(psrhac1r);}	var myElementpsrhac1p = document.getElementById("psrhac1p");if(myElementpsrhac1p){ document.getElementById("psrhac1d").textContent = psrhac1t;document.getElementById("psrhac1p").classList.add(psrhac1r);var a = document.getElementById('psrhac1d');a.href = psrhac1a;document.getElementById("psrhac1r").textContent = psrhac1c}
let psrhgi1r="Gamedraco"; let psrhgi1c="Gamedraco"; let psrhgi1t="1:31.18"; let psrhgi1a="https://www.youtube.com/watch?v=koiaHQzfUGw";	var myElementpsrhgi1 = document.getElementById("psrhgi1");if(myElementpsrhgi1){ document.getElementById("psrhgi1l").textContent = psrhgi1t;document.getElementById("psrhgi1").classList.add(psrhgi1r);}	var myElementpsrhgi1p = document.getElementById("psrhgi1p");if(myElementpsrhgi1p){ document.getElementById("psrhgi1d").textContent = psrhgi1t;document.getElementById("psrhgi1p").classList.add(psrhgi1r);var a = document.getElementById('psrhgi1d');a.href = psrhgi1a;document.getElementById("psrhgi1r").textContent = psrhgi1c}    
    
    
    
    
    
    
    
    
    
    
    
    
//let dcbfgi1r="AxlThunder"; let dcbfgi1t="1:21.52"; let dcbfgi1a="https://www.youtube.com/watch?v=0qVxl6PueuQ";	var myElementdcbfgi1 = document.getElementById("dcbfgi1");if(myElementdcbfgi1){ document.getElementById("dcbfgi1l").textContent = dcbfgi1t;document.getElementById("dcbfgi1").classList.add(dcbfgi1r);}	var myElementdcbfgi1p = document.getElementById("dcbfgi1p");if(myElementdcbfgi1p){ document.getElementById("dcbfgi1d").textContent = dcbfgi1t;document.getElementById("dcbfgi1p").classList.add(dcbfgi1r);}var a = document.getElementById('dcbfgi1d');a.href = dcbfgi1a}
//let dcbfli1r="AxlThunder"; let dcbfli1t="1:24.08"; let dcbfli1a="https://www.youtube.com/watch?v=8xgGGFmWdzQ";	var myElementdcbfli1 = document.getElementById("dcbfli1");if(myElementdcbfli1){ document.getElementById("dcbfli1l").textContent = dcbfli1t;document.getElementById("dcbfli1").classList.add(dcbfli1r);}	var myElementdcbfli1p = document.getElementById("dcbfli1p");if(myElementdcbfli1p){ document.getElementById("dcbfli1d").textContent = dcbfli1t;document.getElementById("dcbfli1p").classList.add(dcbfli1r);}var a = document.getElementById('dcbfli1d');a.href = dcbfli1a}
//let dcbfsg1r="AxlThunder"; let dcbfsg1t="1:26.75"; let dcbfsg1a="https://www.youtube.com/watch?v=UuzAz5GfNog";	var myElementdcbfsg1 = document.getElementById("dcbfsg1");if(myElementdcbfsg1){ document.getElementById("dcbfsg1l").textContent = dcbfsg1t;document.getElementById("dcbfsg1").classList.add(dcbfsg1r);}	var myElementdcbfsg1p = document.getElementById("dcbfsg1p");if(myElementdcbfsg1p){ document.getElementById("dcbfsg1d").textContent = dcbfsg1t;document.getElementById("dcbfsg1p").classList.add(dcbfsg1r);}var a = document.getElementById('dcbfsg1d');a.href = dcbfsg1a}
//let dcrhgi1r="AxlThunder"; let dcrhgi1t="1:26.25"; let dcrhgi1a="https://www.youtube.com/watch?v=B2_evQM4d88";	var myElementdcrhgi1 = document.getElementById("dcrhgi1");if(myElementdcrhgi1){ document.getElementById("dcrhgi1l").textContent = dcrhgi1t;document.getElementById("dcrhgi1").classList.add(dcrhgi1r);}	var myElementdcrhgi1p = document.getElementById("dcrhgi1p");if(myElementdcrhgi1p){ document.getElementById("dcrhgi1d").textContent = dcrhgi1t;document.getElementById("dcrhgi1p").classList.add(dcrhgi1r);}var a = document.getElementById('dcrhgi1d');a.href = dcrhgi1a}
//let nibfna1r="Gamedraco"; let nibfna1t="2:44.40"; let nibfna1a="https://www.youtube.com/watch?v=xeFMb4eP05Y&t=1s";	var myElementnibfna1 = document.getElementById("nibfna1");if(myElementnibfna1){ document.getElementById("nibfna1l").textContent = nibfna1t;document.getElementById("nibfna1").classList.add(nibfna1r);}	var myElementnibfna1p = document.getElementById("nibfna1p");if(myElementnibfna1p){ document.getElementById("nibfna1d").textContent = nibfna1t;document.getElementById("nibfna1p").classList.add(nibfna1r);}var a = document.getElementById('nibfna1d');a.href = nibfna1a}
//let nirhac1r="Gamedraco"; let nirhac1t="1:33.79"; let nirhac1a="https://www.youtube.com/watch?v=nOOIJa7WsMo";	var myElementnirhac1 = document.getElementById("nirhac1");if(myElementnirhac1){ document.getElementById("nirhac1l").textContent = nirhac1t;document.getElementById("nirhac1").classList.add(nirhac1r);}	var myElementnirhac1p = document.getElementById("nirhac1p");if(myElementnirhac1p){ document.getElementById("nirhac1d").textContent = nirhac1t;document.getElementById("nirhac1p").classList.add(nirhac1r);var a = document.getElementById('nirhac1d');a.href = nirhac1a}
//                                                                                                                var myElementnitbli1 = document.getElementById("nitbli1");if(myElementnitbli1){ document.getElementById("nitbli1l").textContent = nitbli1t;document.getElementById("nitbli1").classList.add(nitbli1r);}	var myElementnitbli1p = document.getElementById("nitbli1p");if(myElementnitbli1p){ document.getElementById("nitbli1d").textContent = nitbli1t;document.getElementById("nitbli1p").classList.add(nitbli1r);var a = document.getElementById('nitbli1d');a.href = nitbli1a}   
//let nirhfe1r="Gamedraco"; let nirhfe1t="1:25.43"; let nirhfe1a="https://www.youtube.com/watch?v=OKjYxLI12ak";	var myElementnirhfe1 = document.getElementById("nirhfe1");if(myElementnirhfe1){ document.getElementById("nirhfe1l").textContent = nirhfe1t;document.getElementById("nirhfe1").classList.add(nirhfe1r);}	var myElementnirhfe1p = document.getElementById("nirhfe1p");if(myElementnirhfe1p){ document.getElementById("nirhfe1d").textContent = nirhfe1t;document.getElementById("nirhfe1p").classList.add(nirhfe1r);}var a = document.getElementById('nirhfe1d');a.href = nirhfe1a}
//let nitbac1r="LazyComet"; let nitbac1t="1:50.32"; let nitbac1a="https://www.twitch.tv/videos/1441988243";	var myElementnitbac1 = document.getElementById("nitbac1");if(myElementnitbac1){ document.getElementById("nitbac1l").textContent = nitbac1t;document.getElementById("nitbac1").classList.add(nitbac1r);}	var myElementnitbac1p = document.getElementById("nitbac1p");if(myElementnitbac1p){ document.getElementById("nitbac1d").textContent = nitbac1t;document.getElementById("nitbac1p").classList.add(nitbac1r);}var a = document.getElementById('nitbac1d');a.href = nitbac1a}
//let nitbfe1r="LazyComet"; let nitbfe1t="1:39.82"; let nitbfe1a="https://www.twitch.tv/videos/1445009096";	var myElementnitbfe1 = document.getElementById("nitbfe1");if(myElementnitbfe1){ document.getElementById("nitbfe1l").textContent = nitbfe1t;document.getElementById("nitbfe1").classList.add(nitbfe1r);}	var myElementnitbfe1p = document.getElementById("nitbfe1p");if(myElementnitbfe1p){ document.getElementById("nitbfe1d").textContent = nitbfe1t;document.getElementById("nitbfe1p").classList.add(nitbfe1r);}var a = document.getElementById('nitbfe1d');a.href = nitbfe1a}
//let nitbgi1r="LazyComet"; let nitbgi1t="1:41.85"; let nitbgi1a="https://www.twitch.tv/videos/1445009095";	var myElementnitbgi1 = document.getElementById("nitbgi1");if(myElementnitbgi1){ document.getElementById("nitbgi1l").textContent = nitbgi1t;document.getElementById("nitbgi1").classList.add(nitbgi1r);}	var myElementnitbgi1p = document.getElementById("nitbgi1p");if(myElementnitbgi1p){ document.getElementById("nitbgi1d").textContent = nitbgi1t;document.getElementById("nitbgi1p").classList.add(nitbgi1r);}var a = document.getElementById('nitbgi1d');a.href = nitbgi1a}
//let nitbli1r="LazyComet"; let nitbli1t="1:46.06"; let nitbli1a="https://www.twitch.tv/videos/1441988245";	var myElementnitbli1 = document.getElementById("nitbli1");if(myElementnitbli1){ document.getElementById("nitbli1l").textContent = nitbli1t;document.getElementById("nitbli1").classList.add(nitbli1r);}	var myElementnitbli1p = document.getElementById("nitbli1p");if(myElementnitbli1p){ document.getElementById("nitbli1d").textContent = nitbli1t;document.getElementById("nitbli1p").classList.add(nitbli1r);}var a = document.getElementById('nitbli1d');a.href = nitbli1a}
//let nitblp1r="LazyComet"; let nitblp1t="1:54.78"; let nitblp1a="https://www.twitch.tv/videos/1445009092";	var myElementnitblp1 = document.getElementById("nitblp1");if(myElementnitblp1){ document.getElementById("nitblp1l").textContent = nitblp1t;document.getElementById("nitblp1").classList.add(nitblp1r);}	var myElementnitblp1p = document.getElementById("nitblp1p");if(myElementnitblp1p){ document.getElementById("nitblp1d").textContent = nitblp1t;document.getElementById("nitblp1p").classList.add(nitblp1r);}var a = document.getElementById('nitblp1d');a.href = nitblp1a}
//let nitbna1r="LazyComet"; let nitbna1t="3:15.76"; let nitbna1a="https://www.twitch.tv/videos/1441988246";	var myElementnitbna1 = document.getElementById("nitbna1");if(myElementnitbna1){ document.getElementById("nitbna1l").textContent = nitbna1t;document.getElementById("nitbna1").classList.add(nitbna1r);}	var myElementnitbna1p = document.getElementById("nitbna1p");if(myElementnitbna1p){ document.getElementById("nitbna1d").textContent = nitbna1t;document.getElementById("nitbna1p").classList.add(nitbna1r);}var a = document.getElementById('nitbna1d');a.href = nitbna1a}
//let nitbny1r="LazyComet"; let nitbny1t="1:48.75"; let nitbny1a="https://www.twitch.tv/videos/1445009093";	var myElementnitbny1 = document.getElementById("nitbny1");if(myElementnitbny1){ document.getElementById("nitbny1l").textContent = nitbny1t;document.getElementById("nitbny1").classList.add(nitbny1r);}	var myElementnitbny1p = document.getElementById("nitbny1p");if(myElementnitbny1p){ document.getElementById("nitbny1d").textContent = nitbny1t;document.getElementById("nitbny1p").classList.add(nitbny1r);}var a = document.getElementById('nitbny1d');a.href = nitbny1a}
//let nitbsg1r="LazyComet"; let nitbsg1t="1:41.96"; let nitbsg1a="https://www.twitch.tv/videos/1445009094";	var myElementnitbsg1 = document.getElementById("nitbsg1");if(myElementnitbsg1){ document.getElementById("nitbsg1l").textContent = nitbsg1t;document.getElementById("nitbsg1").classList.add(nitbsg1r);}	var myElementnitbsg1p = document.getElementById("nitbsg1p");if(myElementnitbsg1p){ document.getElementById("nitbsg1d").textContent = nitbsg1t;document.getElementById("nitbsg1p").classList.add(nitbsg1r);}var a = document.getElementById('nitbsg1d');a.href = nitbsg1a}
//let nitbvc1r="LazyComet"; let nitbvc1t="1:30.99"; let nitbvc1a="https://www.twitch.tv/videos/1445009090";	var myElementnitbvc1 = document.getElementById("nitbvc1");if(myElementnitbvc1){ document.getElementById("nitbvc1l").textContent = nitbvc1t;document.getElementById("nitbvc1").classList.add(nitbvc1r);}	var myElementnitbvc1p = document.getElementById("nitbvc1p");if(myElementnitbvc1p){ document.getElementById("nitbvc1d").textContent = nitbvc1t;document.getElementById("nitbvc1p").classList.add(nitbvc1r);}var a = document.getElementById('nitbvc1d');a.href = nitbvc1a}
//let pcarli1r="AxlThunder"; let pcarli1t="1:36.86"; let pcarli1a="https://www.youtube.com/watch?v=iHgbVQKXUWo";	var myElementpcarli1 = document.getElementById("pcarli1");if(myElementpcarli1){ document.getElementById("pcarli1l").textContent = pcarli1t;document.getElementById("pcarli1").classList.add(pcarli1r);}	var myElementpcarli1p = document.getElementById("pcarli1p");if(myElementpcarli1p){ document.getElementById("pcarli1d").textContent = pcarli1t;document.getElementById("pcarli1p").classList.add(pcarli1r);}var a = document.getElementById('pcarli1d');a.href = pcarli1a}
//let pcarvc1r="WeenieWhistle"; let pcarvc1t="1:19.43"; let pcarvc1a="https://youtu.be/rl6L6onWTyo";	var myElementpcarvc1 = document.getElementById("pcarvc1");if(myElementpcarvc1){ document.getElementById("pcarvc1l").textContent = pcarvc1t;document.getElementById("pcarvc1").classList.add(pcarvc1r);}	var myElementpcarvc1p = document.getElementById("pcarvc1p");if(myElementpcarvc1p){ document.getElementById("pcarvc1d").textContent = pcarvc1t;document.getElementById("pcarvc1p").classList.add(pcarvc1r);}var a = document.getElementById('pcarvc1d');a.href = pcarvc1a}
//let pcarvc2r="AxlThunder"; let pcarvc2t="1:19.89"; let pcarvc2a="https://www.youtube.com/watch?v=Sl1HWo1ZihE";	var myElementpcarvc2 = document.getElementById("pcarvc2");if(myElementpcarvc2){ document.getElementById("pcarvc2l").textContent = pcarvc2t;document.getElementById("pcarvc2").classList.add(pcarvc2r);}	var myElementpcarvc2p = document.getElementById("pcarvc2p");if(myElementpcarvc2p){ document.getElementById("pcarvc2d").textContent = pcarvc2t;document.getElementById("pcarvc2p").classList.add(pcarvc2r);}var a = document.getElementById('pcarvc2d');a.href = pcarvc2a}
//let pcctgi1r="AxlThunder"; let pcctgi1t="1:17.39"; let pcctgi1a="https://www.youtube.com/watch?v=SIO4W85xzmg";	var myElementpcctgi1 = document.getElementById("pcctgi1");if(myElementpcctgi1){ document.getElementById("pcctgi1l").textContent = pcctgi1t;document.getElementById("pcctgi1").classList.add(pcctgi1r);}	var myElementpcctgi1p = document.getElementById("pcctgi1p");if(myElementpcctgi1p){ document.getElementById("pcctgi1d").textContent = pcctgi1t;document.getElementById("pcctgi1p").classList.add(pcctgi1r);}var a = document.getElementById('pcctgi1d');a.href = pcctgi1a}
//let pcrbli1r="AxlThunder"; let pcrbli1t="1:31.89"; let pcrbli1a="https://www.youtube.com/watch?v=V1flcTZ8TCw";	var myElementpcrbli1 = document.getElementById("pcrbli1");if(myElementpcrbli1){ document.getElementById("pcrbli1l").textContent = pcrbli1t;document.getElementById("pcrbli1").classList.add(pcrbli1r);}	var myElementpcrbli1p = document.getElementById("pcrbli1p");if(myElementpcrbli1p){ document.getElementById("pcrbli1d").textContent = pcrbli1t;document.getElementById("pcrbli1p").classList.add(pcrbli1r);}var a = document.getElementById('pcrbli1d');a.href = pcrbli1a}
//let pcrhli1r="AxlThunder"; let pcrhli1t="1:26.86"; let pcrhli1a="https://www.youtube.com/watch?v=M5Fn4Lfc4Eo";	var myElementpcrhli1 = document.getElementById("pcrhli1");if(myElementpcrhli1){ document.getElementById("pcrhli1l").textContent = pcrhli1t;document.getElementById("pcrhli1").classList.add(pcrhli1r);}	var myElementpcrhli1p = document.getElementById("pcrhli1p");if(myElementpcrhli1p){ document.getElementById("pcrhli1d").textContent = pcrhli1t;document.getElementById("pcrhli1p").classList.add(pcrhli1r);}var a = document.getElementById('pcrhli1d');a.href = pcrhli1a}
//let pctbli1r="AxlThunder"; let pctbli1t="1:33.32"; let pctbli1a="https://www.youtube.com/watch?v=EpnQNmZM6xU";	var myElementpctbli1 = document.getElementById("pctbli1");if(myElementpctbli1){ document.getElementById("pctbli1l").textContent = pctbli1t;document.getElementById("pctbli1").classList.add(pctbli1r);}	var myElementpctbli1p = document.getElementById("pctbli1p");if(myElementpctbli1p){ document.getElementById("pctbli1d").textContent = pctbli1t;document.getElementById("pctbli1p").classList.add(pctbli1r);}var a = document.getElementById('pctbli1d');a.href = pctbli1a}
//let pctblp1r="AxlThunder"; let pctblp1t="1:38.79"; let pctblp1a="https://www.youtube.com/watch?v=sTNq-KkcWXo";	var myElementpctblp1 = document.getElementById("pctblp1");if(myElementpctblp1){ document.getElementById("pctblp1l").textContent = pctblp1t;document.getElementById("pctblp1").classList.add(pctblp1r);}	var myElementpctblp1p = document.getElementById("pctblp1p");if(myElementpctblp1p){ document.getElementById("pctblp1d").textContent = pctblp1t;document.getElementById("pctblp1p").classList.add(pctblp1r);}var a = document.getElementById('pctblp1d');a.href = pctblp1a}
//let psrhac1r="Gamedraco"; let psrhac1t="1:36.42"; let psrhac1a="https://www.youtube.com/watch?v=zGz7anGg2co";	var myElementpsrhac1 = document.getElementById("psrhac1");if(myElementpsrhac1){ document.getElementById("psrhac1l").textContent = psrhac1t;document.getElementById("psrhac1").classList.add(psrhac1r);}	var myElementpsrhac1p = document.getElementById("psrhac1p");if(myElementpsrhac1p){ document.getElementById("psrhac1d").textContent = psrhac1t;document.getElementById("psrhac1p").classList.add(psrhac1r);}var a = document.getElementById('psrhac1d');a.href = psrhac1a}
//let psrhgi1r="Gamedraco"; let psrhgi1t="1:31.18"; let psrhgi1a="https://www.youtube.com/watch?v=koiaHQzfUGw";	var myElementpsrhgi1 = document.getElementById("psrhgi1");if(myElementpsrhgi1){ document.getElementById("psrhgi1l").textContent = psrhgi1t;document.getElementById("psrhgi1").classList.add(psrhgi1r);}	var myElementpsrhgi1p = document.getElementById("psrhgi1p");if(myElementpsrhgi1p){ document.getElementById("psrhgi1d").textContent = psrhgi1t;document.getElementById("psrhgi1p").classList.add(psrhgi1r);}var a = document.getElementById('psrhgi1d');a.href = psrhgi1a}
    
 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*let dcbfgi1r="AxlThunder"; let dcbfgi1t="1:21.52"; let dcbfgi1a="https://www.youtube.com/watch?v=0qVxl6PueuQ";
let dcbfli1r="AxlThunder"; let dcbfli1t="1:24.08"; let dcbfli1a="https://www.youtube.com/watch?v=8xgGGFmWdzQ";
let dcbfsg1r="AxlThunder"; let dcbfsg1t="1:26.75"; let dcbfsg1a="https://www.youtube.com/watch?v=UuzAz5GfNog";
let dcrhgi1r="AxlThunder"; let dcrhgi1t="1:26.25"; let dcrhgi1a="https://www.youtube.com/watch?v=B2_evQM4d88";
let nibfna2r="Gamedraco"; let nibfna2t="2:44.40"; let nibfna2a="https://www.youtube.com/watch?v=xeFMb4eP05Y&t=1s";
let nirhac1r="Gamedraco"; let nirhac1t="1:33.79"; let nirhac1a="https://www.youtube.com/watch?v=nOOIJa7WsMo";
let nirhfe1r="Gamedraco"; let nirhfe1t="1:25.43"; let nirhfe1a="https://www.youtube.com/watch?v=OKjYxLI12ak";
let nitbac1r="LazyComet"; let nitbac1t="1:50.32"; let nitbac1a="https://www.twitch.tv/videos/1441988243";
let nitbfe1r="LazyComet"; let nitbfe1t="1:39.82"; let nitbfe1a="https://www.twitch.tv/videos/1445009096";
let nitbgi1r="LazyComet"; let nitbgi1t="1:41.85"; let nitbgi1a="https://www.twitch.tv/videos/1445009095";
let nitbli1r="LazyComet"; let nitbli1t="1:46.06"; let nitbli1a="https://www.twitch.tv/videos/1441988245";
let nitblp1r="LazyComet"; let nitblp1t="1:54.78"; let nitblp1a="https://www.twitch.tv/videos/1445009092";
let nitbna1r="LazyComet"; let nitbna1t="3:15.76"; let nitbna1a="https://www.twitch.tv/videos/1441988246";
let nitbny1r="LazyComet"; let nitbny1t="1:48.75"; let nitbny1a="https://www.twitch.tv/videos/1445009093";
let nitbsg1r="LazyComet"; let nitbsg1t="1:41.96"; let nitbsg1a="https://www.twitch.tv/videos/1445009094";
let nitbvc1r="LazyComet"; let nitbvc1t="1:30.99"; let nitbvc1a="https://www.twitch.tv/videos/1445009090";
let pcarli1r="AxlThunder"; let pcarli1t="1:36.86"; let pcarli1a="https://www.youtube.com/watch?v=iHgbVQKXUWo";
let pcarvc1r="WeenieWhistle"; let pcarvc1t="1:19.43"; let pcarvc1a="https://youtu.be/rl6L6onWTyo";
let pcarvc2r="AxlThunder"; let pcarvc2t="1:19.89"; let pcarvc2a="https://www.youtube.com/watch?v=Sl1HWo1ZihE";
let pcctgi1r="AxlThunder"; let pcctgi1t="1:17.39"; let pcctgi1a="https://www.youtube.com/watch?v=SIO4W85xzmg";
let pcrbli1r="AxlThunder"; let pcrbli1t="1:31.89"; let pcrbli1a="https://www.youtube.com/watch?v=V1flcTZ8TCw";
let pcrhli1r="AxlThunder"; let pcrhli1t="1:26.86"; let pcrhli1a="https://www.youtube.com/watch?v=M5Fn4Lfc4Eo";
let pctbli1r="AxlThunder"; let pctbli1t="1:33.32"; let pctbli1a="https://www.youtube.com/watch?v=EpnQNmZM6xU";
let pctblp1r="AxlThunder"; let pctblp1t="1:38.79"; let pctblp1a="https://www.youtube.com/watch?v=sTNq-KkcWXo";
let psrhac1r="Gamedraco"; let psrhac1t="1:36.42"; let psrhac1a="https://www.youtube.com/watch?v=zGz7anGg2co";
let psrhgi1r="Gamedraco"; let psrhgi1t="1:31.18"; let psrhgi1a="https://www.youtube.com/watch?v=koiaHQzfUGw";    
    

//var myElementnitbli1p = document.getElementById("nitbli1p");if(myElementnitbli1p){ document.getElementById("nitbli1d").textContent = nitbli1t;document.getElementById("nitbli1p").classList.add(nitbli1r);var a = document.getElementById('nitbli1d');a.href = nitbli1a}    
var myElementnitbli1 = document.getElementById("nitbli1");if(myElementnitbli1){ document.getElementById("nitbli1l").textContent = nitbli1t;document.getElementById("nitbli1").classList.add(nitbli1r);}	  var myElementnitbli1p = document.getElementById("nitbli1p");if(myElementnitbli1p){ document.getElementById("nitbli1d").textContent = nitbli1t;document.getElementById("nitbli1p").classList.add(nitbli1r);var a = document.getElementById('nitbli1d');a.href = nitbli1a}   
    
    
    
    
    
//var myElementdcbfgi1 = document.getElementById("dcbfgi1");if(myElementdcbfgi1){ document.getElementById("dcbfgi1l").textContent = dcbfgi1t;document.getElementById("dcbfgi1").classList.add(dcbfgi1r);}
//var myElementdcbfli1 = document.getElementById("dcbfli1");if(myElementdcbfli1){ document.getElementById("dcbfli1l").textContent = dcbfli1t;document.getElementById("dcbfli1").classList.add(dcbfli1r);}
//var myElementdcbfsg1 = document.getElementById("dcbfsg1");if(myElementdcbfsg1){ document.getElementById("dcbfsg1l").textContent = dcbfsg1t;document.getElementById("dcbfsg1").classList.add(dcbfsg1r);}
//var myElementdcrhgi1 = document.getElementById("dcrhgi1");if(myElementdcrhgi1){ document.getElementById("dcrhgi1l").textContent = dcrhgi1t;document.getElementById("dcrhgi1").classList.add(dcrhgi1r);}
////var myElementnibfna1 = document.getElementById("nibfna1");if(myElementnibfna1){ document.getElementById("nibfna1l").textContent = nibfna1t;document.getElementById("nibfna1").classList.add(nibfna1r);}
var myElementnirhac1 = document.getElementById("nirhac1");if(myElementnirhac1){ document.getElementById("nirhac1l").textContent = nirhac1t;document.getElementById("nirhac1").classList.add(nirhac1r);}
var myElementnirhfe1 = document.getElementById("nirhfe1");if(myElementnirhfe1){ document.getElementById("nirhfe1l").textContent = nirhfe1t;document.getElementById("nirhfe1").classList.add(nirhfe1r);}
var myElementnitbac1 = document.getElementById("nitbac1");if(myElementnitbac1){ document.getElementById("nitbac1l").textContent = nitbac1t;document.getElementById("nitbac1").classList.add(nitbac1r);}
var myElementnitbfe1 = document.getElementById("nitbfe1");if(myElementnitbfe1){ document.getElementById("nitbfe1l").textContent = nitbfe1t;document.getElementById("nitbfe1").classList.add(nitbfe1r);}
var myElementnitbgi1 = document.getElementById("nitbgi1");if(myElementnitbgi1){ document.getElementById("nitbgi1l").textContent = nitbgi1t;document.getElementById("nitbgi1").classList.add(nitbgi1r);}
//var myElementnitbli1 = document.getElementById("nitbli1");if(myElementnitbli1){ document.getElementById("nitbli1l").textContent = nitbli1t;document.getElementById("nitbli1").classList.add(nitbli1r);}
var myElementnitblp1 = document.getElementById("nitblp1");if(myElementnitblp1){ document.getElementById("nitblp1l").textContent = nitblp1t;document.getElementById("nitblp1").classList.add(nitblp1r);}
var myElementnitbna1 = document.getElementById("nitbna1");if(myElementnitbna1){ document.getElementById("nitbna1l").textContent = nitbna1t;document.getElementById("nitbna1").classList.add(nitbna1r);}
var myElementnitbny1 = document.getElementById("nitbny1");if(myElementnitbny1){ document.getElementById("nitbny1l").textContent = nitbny1t;document.getElementById("nitbny1").classList.add(nitbny1r);}
var myElementnitbsg1 = document.getElementById("nitbsg1");if(myElementnitbsg1){ document.getElementById("nitbsg1l").textContent = nitbsg1t;document.getElementById("nitbsg1").classList.add(nitbsg1r);}
var myElementnitbvc1 = document.getElementById("nitbvc1");if(myElementnitbvc1){ document.getElementById("nitbvc1l").textContent = nitbvc1t;document.getElementById("nitbvc1").classList.add(nitbvc1r);}
var myElementpcarli1 = document.getElementById("pcarli1");if(myElementpcarli1){ document.getElementById("pcarli1l").textContent = pcarli1t;document.getElementById("pcarli1").classList.add(pcarli1r);}
var myElementpcarvc1 = document.getElementById("pcarvc1");if(myElementpcarvc1){ document.getElementById("pcarvc1l").textContent = pcarvc1t;document.getElementById("pcarvc1").classList.add(pcarvc1r);}
var myElementpcarvc2 = document.getElementById("pcarvc2");if(myElementpcarvc2){ document.getElementById("pcarvc2l").textContent = pcarvc2t;document.getElementById("pcarvc2").classList.add(pcarvc2r);}
var myElementpcctgi1 = document.getElementById("pcctgi1");if(myElementpcctgi1){ document.getElementById("pcctgi1l").textContent = pcctgi1t;document.getElementById("pcctgi1").classList.add(pcctgi1r);}
var myElementpcrbli1 = document.getElementById("pcrbli1");if(myElementpcrbli1){ document.getElementById("pcrbli1l").textContent = pcrbli1t;document.getElementById("pcrbli1").classList.add(pcrbli1r);}
var myElementpcrhli1 = document.getElementById("pcrhli1");if(myElementpcrhli1){ document.getElementById("pcrhli1l").textContent = pcrhli1t;document.getElementById("pcrhli1").classList.add(pcrhli1r);}
var myElementpctbli1 = document.getElementById("pctbli1");if(myElementpctbli1){ document.getElementById("pctbli1l").textContent = pctbli1t;document.getElementById("pctbli1").classList.add(pctbli1r);}
var myElementpctblp1 = document.getElementById("pctblp1");if(myElementpctblp1){ document.getElementById("pctblp1l").textContent = pctblp1t;document.getElementById("pctblp1").classList.add(pctblp1r);}
var myElementpsrhac1 = document.getElementById("psrhac1");if(myElementpsrhac1){ document.getElementById("psrhac1l").textContent = psrhac1t;document.getElementById("psrhac1").classList.add(psrhac1r);}
var myElementpsrhgi1 = document.getElementById("psrhgi1");if(myElementpsrhgi1){ document.getElementById("psrhgi1l").textContent = psrhgi1t;document.getElementById("psrhgi1").classList.add(psrhgi1r);}    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
 // document.getElementById("nibfna1l").textContent = nibfna1t; document.getElementById("nibfna1").classList.add(nibfna1r);
    
    //var myElement = document.getElementById("nirhac1");if(myElement){ document.getElementById("nirhac1l").textContent = nirhac1t; document.getElementById("nirhac1").classList.add(nirhac1r);}
  //document.getElementById("nirhfe1l").textContent = nirhfe1t; document.getElementById("nirhfe1").classList.add(nirhfe1r);
  //document.getElementById("nitbac1l").textContent = nitbac1t; document.getElementById("nitbac1").classList.add(nitbac1r);
//  document.getElementById("nitbfe1l").textContent = nitbfe1t; document.getElementById("nitbfe1").classList.add(nitbfe1r);
//  document.getElementById("nitbgi1l").textContent = nitbgi1t; document.getElementById("nitbgi1").classList.add(nitbgi1r);
 // document.getElementById("nitbli1l").textContent = nitbli1t; document.getElementById("nitbli1").classList.add(nitbli1r);
  //document.getElementById("nitbna1l").textContent = nitbna1t; document.getElementById("nitbna1").classList.add(nitbna1r);    
    
  //document.getElementById("nitbny1l").textContent = nitbny1t; document.getElementById("nitbny1").classList.add(nitbny1r);
//document.getElementById("nitbsg1l").textContent = nitbsg1t; document.getElementById("nitbsg1").classList.add(nitbsg1r);
//document.getElementById("nitbvc1l").textContent = nitbvc1t; document.getElementById("nitbvc1").classList.add(nitbvc1r);
 //   document.getElementById("nitblp1l").textContent = nitblp1t; document.getElementById("nitblp1").classList.add(nitblp1r);
   // document.getElementById("nitbgi1l").textContent = nitbgi1t; document.getElementById("nitbgi1").classList.add(nitbgi1r);
   // document.getElementById("nitbfe1l").textContent = nitbfe1t; document.getElementById("nitbfe1").classList.add(nitbfe1r);
    
    
    
    
    
    
    
    
    
    document.getElementById("nibftp1").classList.add('AxlThunder');
    document.getElementById("nibfli1").classList.add('AxlThunder');
    document.getElementById("nibfac1").classList.add('AxlThunder');
    document.getElementById("nibfgi1").classList.add('AxlThunder');
    document.getElementById("nibflp1").classList.add('AxlThunder');
    document.getElementById("nibffe1").classList.add('AxlThunder');
    document.getElementById("nibfsg1").classList.add('AxlThunder');
    document.getElementById("nibfvc1").classList.add('AxlThunder');
    document.getElementById("nibfny1").classList.add('AxlThunder');
    document.getElementById("nibfcc1").classList.add('AxlThunder');
    document.getElementById("nibfhs1").classList.add('AxlThunder');
    document.getElementById("nibfna1").classList.add('AxlThunder');

    document.getElementById("nictgi1").classList.add('Inphlox');
    document.getElementById("nirhgi1").classList.add('Inphlox');
    document.getElementById("nibfcd1").classList.add('Inphlox');
    
    
 
   //document.getElementById("nirhfe1l").textContent = nirhfe1t;document.getElementById("nirhfe1").classList.add(nirhfe1r);
    //document.getElementById("nirhac1l").textContent = nirhacft;document.getElementById("nirhac1").classList.add(nirhacfr);

    
//                          cell link id                  track time                       cell ID           track runner
//  document.getElementById("nidttp1l").textContent = nidttp1t; document.getElementById("nidttp1").classList.add(nidttp1r);

*/
}



